var CRAFT_DATA = {
"pot_heal_1": { "type": "brew", "level": 1, "reagents": [ ["ccc_h2o", 1], ["ccc_herb1", 1] ] },
"pot_heal_2": { "type": "brew", "level": 2, "reagents": [ ["ccc_h2o", 1], ["ccc_herb1", 2] ] },
"pot_heal_3": { "type": "brew", "level": 3, "reagents": [ ["ccc_h2o", 1], ["ccc_herb1", 4] ] },
"pot_regen_1": { "type": "brew", "level": 1, "reagents": [ ["ccc_h2o", 1], ["ccc_herb1", 2] ] },
"pot_regen_2": { "type": "brew", "level": 2, "reagents": [ ["ccc_h2o", 1], ["ccc_herb1", 3] ] },
"pot_regen_3": { "type": "brew", "level": 3, "reagents": [ ["ccc_h2o", 1], ["ccc_herb1", 6] ] },
"pot_ether_1": { "type": "brew", "level": 1, "reagents": [ ["ccc_h2o", 1], ["ccc_herb1", 1], ["ccc_herb2", 1] ] },
"pot_ether_2": { "type": "brew", "level": 2, "reagents": [ ["ccc_h2o", 1], ["ccc_herb1", 1], ["ccc_herb2", 2] ] },
"pot_ether_3": { "type": "brew", "level": 3, "reagents": [ ["ccc_h2o", 1], ["ccc_herb1", 4], ["ccc_herb2", 2] ] },
"pot_star_1": { "type": "brew", "level": 3, "reagents": [ ["ccc_holyh2o", 1], ["ccc_herb4", 2] ] },
"pot_star_2": { "type": "brew", "level": 5, "reagents": [ ["ccc_holyh2o", 1], ["ccc_herb4", 3] ] },
"pot_power_1": { "type": "brew", "level": 1, "reagents": [ ["ccc_h2o", 1], ["ccc_herb2", 2] ] },
"pot_power_2": { "type": "brew", "level": 2, "reagents": [ ["ccc_h2o", 1], ["ccc_herb2", 3] ] },
"pot_power_3": { "type": "brew", "level": 3, "reagents": [ ["ccc_h2o", 1], ["ccc_herb2", 4] ] },
"pot_haste": { "type": "brew", "level": 2, "reagents": [ ["ccc_h2o", 1], ["ccc_herb2", 2], ["ccc_herb3", 1] ] },
"pot_esp": { "type": "brew", "level": 1, "reagents": [ ["ccc_holyh2o", 1], ["ccc_herb3", 1] ] },
"pot_vital_1": { "type": "brew", "level": 1, "reagents": [ ["ccc_h2o", 1], ["ccc_herb1", 2], ["ccc_herb2", 1] ] },
"pot_vital_2": { "type": "brew", "level": 2, "reagents": [ ["ccc_h2o", 1], ["ccc_herb1", 3], ["ccc_herb2", 2] ] },
"pot_vital_3": { "type": "brew", "level": 3, "reagents": [ ["ccc_h2o", 1], ["ccc_herb1", 4], ["ccc_herb2", 3] ] },
"pot_luck_1": { "type": "brew", "level": 1, "reagents": [ ["ccc_holyh2o", 1], ["ccc_herb2", 1], ["ccc_herb3", 1] ] },
"pot_luck_2": { "type": "brew", "level": 2, "reagents": [ ["ccc_holyh2o", 1], ["ccc_herb2", 2], ["ccc_herb3", 1] ] },
"pot_luck_3": { "type": "brew", "level": 3, "reagents": [ ["ccc_holyh2o", 1], ["ccc_herb2", 3], ["ccc_herb3", 1] ] },
"pot_antidote": { "type": "brew", "level": 1, "reagents": [ ["ccc_h2o", 1], ["ccc_herb1", 2] ] },
"pot_remedy": { "type": "brew", "level": 2, "reagents": [ ["ccc_holyh2o", 1], ["ccc_herb1", 1], ["ccc_herb2", 2] ] },
"pot_cleansing": { "type": "brew", "level": 2, "reagents": [ ["ccc_holyh2o", 1], ["ccc_herb1", 1], ["ccc_herb3", 2] ] },
"pot_freedom": { "type": "brew", "level": 2, "reagents": [ ["ccc_h2o", 1], ["ccc_herb1", 1], ["ccc_herb2", 1], ["ccc_herb3", 1] ] },
"pot_resphy_1": { "type": "brew", "level": 1, "reagents": [ ["ccc_h2o", 1], ["ccc_herb2", 2], ["ccc_herb5", 1] ] },
"pot_resphy_2": { "type": "brew", "level": 2, "reagents": [ ["ccc_h2o", 1], ["ccc_herb2", 2], ["ccc_herb5", 2] ] },
"pot_resphy_3": { "type": "brew", "level": 3, "reagents": [ ["ccc_h2o", 1], ["ccc_herb2", 2], ["ccc_herb5", 3] ] },
"pot_resfir_1": { "type": "brew", "level": 1, "reagents": [ ["ccc_h2o", 1], ["ccc_herb2", 2], ["ccc_herb5", 1] ] },
"pot_resfir_2": { "type": "brew", "level": 2, "reagents": [ ["ccc_h2o", 1], ["ccc_herb2", 2], ["ccc_herb5", 2] ] },
"pot_resfir_3": { "type": "brew", "level": 3, "reagents": [ ["ccc_h2o", 1], ["ccc_herb2", 2], ["ccc_herb5", 3] ] },
"pot_rescld_1": { "type": "brew", "level": 1, "reagents": [ ["ccc_h2o", 1], ["ccc_herb2", 2], ["ccc_herb5", 1] ] },
"pot_rescld_2": { "type": "brew", "level": 2, "reagents": [ ["ccc_h2o", 1], ["ccc_herb2", 2], ["ccc_herb5", 2] ] },
"pot_rescld_3": { "type": "brew", "level": 3, "reagents": [ ["ccc_h2o", 1], ["ccc_herb2", 2], ["ccc_herb5", 3] ] },
"pot_resele_1": { "type": "brew", "level": 1, "reagents": [ ["ccc_h2o", 1], ["ccc_herb2", 2], ["ccc_herb5", 1] ] },
"pot_resele_2": { "type": "brew", "level": 2, "reagents": [ ["ccc_h2o", 1], ["ccc_herb2", 2], ["ccc_herb5", 2] ] },
"pot_resele_3": { "type": "brew", "level": 3, "reagents": [ ["ccc_h2o", 1], ["ccc_herb2", 2], ["ccc_herb5", 3] ] },
"pot_restox_1": { "type": "brew", "level": 1, "reagents": [ ["ccc_h2o", 1], ["ccc_herb1", 2], ["ccc_herb5", 1] ] },
"pot_restox_2": { "type": "brew", "level": 2, "reagents": [ ["ccc_h2o", 1], ["ccc_herb1", 2], ["ccc_herb5", 2] ] },
"pot_restox_3": { "type": "brew", "level": 3, "reagents": [ ["ccc_h2o", 1], ["ccc_herb1", 2], ["ccc_herb5", 3] ] },
"pot_resmag_1": { "type": "brew", "level": 1, "reagents": [ ["ccc_h2o", 1], ["ccc_herb3", 2], ["ccc_herb5", 1] ] },
"pot_resmag_2": { "type": "brew", "level": 2, "reagents": [ ["ccc_h2o", 1], ["ccc_herb3", 2], ["ccc_herb5", 2] ] },
"pot_resmag_3": { "type": "brew", "level": 3, "reagents": [ ["ccc_h2o", 1], ["ccc_herb3", 2], ["ccc_herb5", 3] ] },
"pot_dispell": { "type": "brew", "level": 1, "reagents": [ ["ccc_h2o", 1], ["ccc_herb3", 1], ["ccc_herb4", 1] ] },
"ccc_meal": { "type": "cook", "level": 1, "reagents": [ ["ccc_meat", 1], ["ccc_vegs", 1], ["ccc_herb0", 1], ["ccc_h2o", 1] ] }
};
