var SPELLS_DATA = {
"mis_warlock_1": { "blueprint": "p_magbolt", "cost": 0, "options": "l1", "effects": ["mxmagCA", "mabldBF", "mavulCF", "maillCF"], "chances": [ 1, 0.1, 0.25, 0.2 ] },
"mis_boomacid_1": { "blueprint": "p_exptoxic", "cost": 0, "options": "l1a4h", "effects": ["axtoxFA"], "chances": [ 1 ] },
"mis_boomfire_1": { "blueprint": "p_expfire", "cost": 0, "options": "l1a4h", "effects": ["axfirFA"], "chances": [ 1 ] },
"mis_impwand_1": { "blueprint": "p_shadbolt", "cost": 0, "options": "l1", "effects": ["mxmagEA"], "chances": [ 1 ] },
"mis_heal_1": { "blueprint": "p_healbolt", "cost": 0, "options": "l1", "effects": ["mrheaEA"], "chances": [ 1 ] },
"mis_cubefire_2": { "blueprint": "p_fireball", "cost": 0, "options": "l3b", "effects": ["mxfirCA"], "chances": [ 1 ] },
"mis_turretfire_1": { "blueprint": "p_firebolt", "cost": 0, "options": "l1", "effects": ["mxfirDA"], "chances": [ 1 ] },
"mis_toxicspit_1": { "blueprint": "p_toxicspit", "cost": 0, "options": "l1", "effects": ["mxtoxBA", "macnfBK"], "chances": [ 1, 0.2 ] },
"mis_medtoxic_2": { "blueprint": "p_medbolt", "cost": 0, "options": "w1", "effects": ["mxphyEA", "pxtoxCU"], "chances": [ 1, 1 ] },
"mis_firespread_2": { "blueprint": "p_fireball", "cost": 5, "options": "l3b", "effects": ["mxfirCA"], "chances": [ 1 ] },
"mis_firebolt_1": { "blueprint": "p_firebolt", "cost": 1, "options": "l1", "effects": ["mxfirBA"], "chances": [ 1 ] },
"mis_firebolt_2": { "blueprint": "p_firebolt", "cost": 1, "options": "l1", "effects": ["mxfirCA"], "chances": [ 1 ] },
"mis_toxicbolt_1": { "blueprint": "p_toxicbolt", "cost": 2, "options": "w2", "effects": ["mxtoxCA"], "chances": [ 1 ] },
"mis_thunbolt_1": { "blueprint": "p_thunbolt", "cost": 2, "options": "l1", "effects": ["mxeleCA"], "chances": [ 1 ] },
"mis_magbolt_1": { "blueprint": "p_magbolt", "cost": 2, "options": "l1", "effects": ["mxmagBA"], "chances": [ 1 ] },
"mis_icebolt_1": { "blueprint": "p_icebolt", "cost": 1, "options": "l1", "effects": ["mxcldBA"], "chances": [ 1 ] },
"mis_shadbolt_1": { "blueprint": "p_shadbolt", "cost": 1, "options": "l1", "effects": ["mxmagBA"], "chances": [ 1 ] },
"mis_iceball_1": { "blueprint": "p_iceball", "cost": 3, "options": "l3", "effects": ["mxcldDA", "masnrDF"], "chances": [ 1, 1 ] },
"mis_lightbolt_1": { "blueprint": "p_lightbolt", "cost": 1, "options": "l1", "effects": ["mxeleCA"], "chances": [ 1 ] },
"mis_thunbolt_3": { "blueprint": "p_thunbolt", "cost": 3, "options": "l5r", "effects": ["mxeleDA"], "chances": [ 1 ] },
"mis_deathspell_1": { "blueprint": "p_deathspell", "cost": 0, "options": "l1", "effects": ["hxdthBA"], "chances": [ 1 ] },
"slash_poison_1": { "blueprint": "p_slash", "cost": 0, "options": "l1h", "effects": ["axphyCA", "pxtoxCF"], "chances": [ 1, 0.25 ] },
"slash_ravenbeak_1": { "blueprint": "p_slash", "cost": 0, "options": "l1h", "effects": ["axphyCA"], "chances": [ 1 ] },
"slash_wand": { "blueprint": "p_slash", "cost": 0, "options": "l1h", "effects": ["xxphyBA"], "chances": [ 1 ] },
"slash_brass": { "blueprint": "p_slash", "cost": 0, "options": "l1h", "effects": ["xxphyCA"], "chances": [ 1 ] },
"slash_kopper": { "blueprint": "p_slash", "cost": 0, "options": "l1h", "effects": ["xxphyCA", "xxeleEA"], "chances": [ 1, 0.25 ] },
"slash_steel": { "blueprint": "p_slash", "cost": 0, "options": "l1h", "effects": ["xxphyDA"], "chances": [ 1 ] },
"slash_sylver": { "blueprint": "p_slash", "cost": 0, "options": "l1h", "effects": ["xxphyEA"], "chances": [ 1 ] },
"slash_jade": { "blueprint": "p_slash", "cost": 0, "options": "l1h", "effects": ["xxphyFA"], "chances": [ 1 ] },
"slash_gawld": { "blueprint": "p_slash", "cost": 0, "options": "l1h", "effects": ["xxphyGA"], "chances": [ 1 ] }
};
