#!/bin/bash

GameWorkPath="../../dynamics/rcwe/games/work/"

# 1: chemin vers le jeu compilé
# 2: nom du jeu
updateFromGame() {
	local sGame="$1"
	local sLevel="$2"
	cp "$sGame/data/world.js" "data/$sLevel.js"
	sed -i -e "s/WORLD_DATA.level/WORLD_DATA.$sLevel/g" "$sLevel.js"
}

listLevels() {
	local i
	for i in `ls $GameWorkPath`
	do
		
	done
}

ls ../../dynamics/rcwe/games/work/




